In [1]:
import numpy as np
import pandas as pd

In [ ]:
#.........................................mean..........................................

# Original list
original_list = [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0]

# Flatten the list
flattened_list = [item for sublist in original_list for item in (sublist if isinstance(sublist, list) else [sublist])]

# Check if the list has fewer than 9 elements and fill with the last element
while len(flattened_list) < 9:
    flattened_list.append(flattened_list[-1])

# Reshape into a 3x3 matrix
matrix = np.array(flattened_list).reshape(3, 3)

print(matrix)
np.mean(matrix)





[[3. 4. 5.]
 [1. 4. 7.]
 [4. 4. 4.]]


4.0

In [15]:
#.........................................mean..........................................

original_list =  [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667]

flattened_list = [item for sublist in original_list for item in (sublist if isinstance(sublist, list) else [sublist])]

while len(flattened_list) < 9:
    flattened_list.append(flattened_list[-1])

matrix = np.array(flattened_list).reshape(3, 3)
print(matrix)
np.var(matrix)

[[6.         6.         6.        ]
 [0.66666667 0.66666667 0.66666667]
 [6.66666667 6.66666667 6.66666667]]


7.2098765432098775

In [16]:
#.........................................standard deviation..........................................

original_list = [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611]


flattened_list = [item for sublist in original_list for item in (sublist if isinstance(sublist, list) else [sublist])]

while len(flattened_list) < 9:
    flattened_list.append(flattened_list[-1])

matrix = np.array(flattened_list).reshape(3, 3)
print(matrix)
np.std(matrix)

[[2.44948974 2.44948974 2.44948974]
 [0.81649658 0.81649658 0.81649658]
 [2.5819889  2.5819889  2.5819889 ]]


0.8028550313610179

In [17]:
#.........................................maximum..........................................

original_list = [[6, 7, 8], [2, 5, 8], 8]

flattened_list = [item for sublist in original_list for item in (sublist if isinstance(sublist, list) else [sublist])]

while len(flattened_list) < 9:
    flattened_list.append(flattened_list[-1])

matrix = np.array(flattened_list).reshape(3, 3)
print(matrix)
np.max(matrix)

[[6 7 8]
 [2 5 8]
 [8 8 8]]


8

In [18]:
#.........................................minimum..........................................

original_list =  [[0, 1, 2], [0, 3, 6], 0]

flattened_list = [item for sublist in original_list for item in (sublist if isinstance(sublist, list) else [sublist])]

while len(flattened_list) < 9:
    flattened_list.append(flattened_list[-1])

matrix = np.array(flattened_list).reshape(3, 3)
print(matrix)
np.min(matrix)

[[0 1 2]
 [0 3 6]
 [0 0 0]]


0

In [19]:
#.........................................sum..........................................

original_list =  [[9, 12, 15], [3, 12, 21], 36]

flattened_list = [item for sublist in original_list for item in (sublist if isinstance(sublist, list) else [sublist])]

while len(flattened_list) < 9:
    flattened_list.append(flattened_list[-1])

matrix = np.array(flattened_list).reshape(3, 3)
print(matrix)
np.sum(matrix)

[[ 9 12 15]
 [ 3 12 21]
 [36 36 36]]


180